config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :auth }
  devise_scope :user do
    get    '/login'       => 'auth#login',  as: :new_user_session
    delete '/logout'      => 'auth#logout', as: :destroy_user_session

    post '/login/email'        => 'auth#send_ios_login_email', as: :send_ios_login_email
    get  '/login/ios/:api_key' => 'auth#login_on_ios',         as: :login_on_ios
  end

  resource :profile, only: [:show]

  resources :teams, only: [:index, :show, :edit, :update]

  get   '/staff'           => 'teams#staff'
  post  '/slack/sync'      => 'teams#sync', as: :sync_slack
  patch '/profile/api_key' => 'profiles#reset_api_key', as: :reset_api_key

  root to: redirect('/staff')
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user     = current_user
    @yardigan = @user.yardigans.first
  end

  def reset_api_key
    current_user.reset_api_key!
    redirect_to :back, notice: "API Key Updated"
  end
end

app/views/profiles/show.html.slim
.col-md-6
  - if @yardigan
    table.table
      thead
        tr
          th
          th
      tbody
        tr
          th Name
          td= @yardigan.name
        tr
          th Email
          td= @yardigan.email
        tr
          th Title
          td= @yardigan.title
        tr
          th Slack
          td= @yardigan.slack_username
        tr
          th Skype
          td= @yardigan.skype_username
        tr
          th Phone
          td= @yardigan.phone_number
    p To update your profile, #{link_to 'edit your account on Slack', @yardigan.remote_profile_path, target: '_blank'} and then either #{link_to 'trigger a Slack sync', sync_slack_path, method: :post} or wait for one to happen automatically.
  - else
    No account data is available. Please contact #{link_to "James", "https://theironyard.slack.com/messages/@james"}.

.col-md-6
  h3
    | API Key 
    = link_to "Reset", reset_api_key_path, class: "btn btn-default btn-sm", method: :patch
  pre= @user.api_key

  p Set header <code>Authorization: bearer #{@user.api_key}</code> to make authenticated API requests.