config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :auth }
  devise_scope :user do
    get    '/login'       => 'auth#login',  as: :new_user_session
    delete '/logout'      => 'auth#logout', as: :destroy_user_session

    post '/login/email'        => 'auth#send_ios_login_email', as: :send_ios_login_email
    get  '/login/ios/:api_key' => 'auth#login_on_ios',         as: :login_on_ios
  end

  resource :profile, only: [:show]

  resources :teams, only: [:index, :show, :edit, :update]

  get   '/staff'           => 'teams#staff'
  post  '/slack/sync'      => 'teams#sync', as: :sync_slack
  patch '/profile/api_key' => 'profiles#reset_api_key', as: :reset_api_key

  root to: redirect('/staff')
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Iron Directory"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"



  body
    = render partial: 'github_ribbon'

    .navbar.navbar-inverse.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" Iron Directory
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              = menu_item "Teams", teams_path
            ul.nav.navbar-nav.pull-right
              - if current_user
                li= link_to current_user.email, profile_path
                li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                li= link_to "Sign In", user_omniauth_authorize_path(:google_oauth2)

    .container
      = bootstrap_flash
      = yield